- ci_build.sh
- configure.ac
Solution: regenerate recipes with recent zproject
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
> Problem: master SHOULD always build

- include/ftydiscovery.h
- src/fty_discovery.cc
- src/ftydiscovery.cc
Solution: Implement ftydiscovery actor, main function and protocol
between them.
> Problem: There is not main actor

- src/device_scan.cc
- src/device_scan.h
- src/fty_discovery.cc
- src/ftydiscovery.cc
- src/range_scan.cc
- src/range_scan.h
write the code for range scan. Now it works from command line. Discovered devices are not send anywhere so far.
> Implementing range scan

- Makefile.am
- project.xml
- src/Makemodule.am
- src/assets.cc
- src/assets.h
- src/fty_discovery_classes.h
- src/fty_discovery_private_selftest.cc
- src/fty_discovery_selftest.cc
Solution: Add assets class and regenerate
> Problem: Need asset cache to get list of known IPs

- src/assets.cc
- src/assets.h
- src/fty_discovery.cc
- src/ftydiscovery.cc
Solution: Ask for republish and delay the start
> Problem: Need list of assets before scan

- src/device_scan.cc
- src/ftydiscovery.cc
- src/range_scan.cc
- src/scan_nut.cc
Solution: Filter existing assets by IP, send "create" message
for new assets. Also minor fixes to get it working.
> Problem: Result of the scan is not propagated further

- src/ftydiscovery.cc
Solution: Process message from actor one level down, respond to REST API request with the obtained value.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: We need to report progress of the scan.

- src/fty-discovery.service.in
> Problem: service file is incomplete

- src/scan_nut.cc
Solution: Use nut driver dump to get something more
> Problem: List of discovered ext attributes is poor

- src/fty_discovery.cc
- src/ftydiscovery.cc
Solution: fix condition, generate nicer names
> Problem: invalid agent condition, ugly names

- src/ftydiscovery.cc
Solution: Use proper way to format int64_t.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Doesn't compile on ARM.

- src/fty_discovery.cc
Solution: Update it, explain quickscan
> Problem: CLI help is not up to date

- src/fty_discovery.cc
- src/ftydiscovery.cc
- src/nutscan.cc
- src/range_scan.cc
Problem : We need more informations on progress and quick reply
Solution :  
-A new scan don't stop current scan anymore, but return status "RUNNING" or "STOPPING" if a scan is not entirely stopped instead. Stop_scan will return a quick reply and will properly stop the scan on a thread.
-Rework of percent in anticipation of multi-range.
> Problem : We need more informations on progress and quick reply

- README.md
- src/ftydiscovery.cc
Problem: Nothing in the README.md
Solution: Add the launch options and protocols description in the README.md
> Problem: Nothing in the README.md

- ci_build.sh
- configure.ac
- packaging/redhat/fty-discovery.spec
Problem: some travis test don't work anymore
Solution: The error come from generation with old gsl version,  redo it with the current gsl version.
> Problem: some travis test don't work anymore

- src/ftydiscovery.cc
> Problem: Stopping scan need to be non-blocking

- README.md
- src/ftydiscovery.cc
- src/range_scan.cc
- src/range_scan.h
Problem: We need a multiscan (range and subnet) management.
Solution: Add treatment of MULTISCAN request and (real) range scan in addition to subnet scan
> Problem: We need a multiscan (range and subnet) management.

- include/ftydiscovery.h
- src/ftydiscovery.cc
Problem: We need to push, get and launch scan configuration instead of 3 scan methods
> Problem: We need to push, get and launch scan configuration instead of 3 scan methods

- README.md
- src/fty-discovery.cfg.in
- src/fty_discovery_server.cc
> Problem: agent can only read config files. Remove setconfig/getconfig.

- include/fty_discovery_library.h
- include/fty_discovery_server.h
- src/device_scan.cc
- src/device_scan.h
- src/fty_discovery_server.cc
- src/range_scan.cc
- src/scan_nut.cc
- src/scan_nut.h
> Problem : we don't want to re-discover device already present

- src/device_scan.cc
- src/device_scan.h
- src/fty_discovery_server.cc
- src/nutscan.cc
- src/nutscan.h
- src/range_scan.cc
- src/scan_nut.cc
- src/scan_nut.h
> Problem: We need a quicker scan

- src/fty_discovery_server.cc
- src/nutscan.cc
- src/scan_nut.cc
Problem : We don't have response from xmlscan for range. But for 1 ip both snmp & xml scan "create" new device
> Problem: Scan XML don't work or duplicate assets

- include/fty_discovery_server.h
- src/fty_discovery_server.cc
> Problem: We need create mode and user

- include/fty_discovery_server.h
- src/fty-discovery.cfg.in
- src/fty_discovery_server.cc
- src/nutdumpdata.cc
- src/nutscan.cc
- src/scan_nut.cc
> Improve discovery speed with a pool of zactor for dumpdata

- src/fty-discovery.cfg.in
- src/nutdumpdata.cc
- src/nutscan.cc
- src/scan_nut.cc
> Correctly close zactor, fix memory leaks and correct small typo

- README.md
- src/subprocess.cc
> Fix Subprocess inconsistency with filedescriptor

- src/fty_discovery_server.cc
- src/scan_nut.cc
> Problem: We need to detect daisy chained device

- src/scan_nut.cc
> correction of daisychained device parsing

- src/fty_discovery_server.cc
- src/scan_nut.cc
> Protect fty-discovery for bad response of dumpdata

- src/subprocess.cc
> Fix inconsistancy of discovery

- src/nutdumpdata.cc
- src/nutscan.cc
Solution: new name used
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>
> Problem: namespace of subprocess changed

- include/fty_discovery_server.h
- src/device_scan.cc
- src/fty-discovery.cfg.in
- src/scan_nut.cc
Depends on 42ity/fty-common-nut#12
> Implement credentials filtering

- include/fty_discovery_server.h
- src/device_scan.cc
- src/fty-discovery.cfg.in
- src/scan_nut.cc
Merge #68 for master first.
Depends on 42ity/fty-common-nut#13.
> Implement credentials filtering for autodiscovery (2.0.1)

- include/fty_discovery_server.h
Fast-track discovery is broken, this fixes it.
> Fix fty-discovery configuration paths

- src/fty_discovery_server.cc
> Fix feed cloning on each fty-discovery invocation (2.1.0)

- src/fty_discovery_server.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Set appropriate error level to log message

- src/fty_discovery_server.cc
Fixes IPMVAL-2563 (hopefully for real this time...).
> Skip SNMP dumps for UPS devices reachable through NetXML

- src/fty_discovery_server.cc
Fixed merge conflicts of https://github.com/42ity/fty-discovery/pull/110
> Release/ipm 2.2.0 (fixed)

- src/scan_nut.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Prevent discovery of duplicated devices within same nut scan loop

- src/fty_discovery.cc
Signed-off-by: Hlib Yarovyi <yarovii.w@gmail.com>
> Fix for PQSWPRG-7932

- src/fty_discovery_server.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Remove fty-asset-accessor call in fty-discovery
